[package]
name = "tessellation"
version = "0.1.0"
authors = ["Casey Primozic <casey@cprimozic.net>"]
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
float-ord = "0.3"
mesh = { path = "../mesh" }
log = "0.4"
