[package]
name = "tessellation"
version = "0.1.0"
authors = ["Casey Primozic <casey@cprimozic.net>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common", features = ["mesh"] }
wasm-bindgen = "=0.2.82"
console_error_panic_hook = "0.1"
float-ord = "0.3"
