[package]
name = "common"
version = "0.1.0"
authors = ["Casey Primozic <casey@cprimozic.net>"]
edition = "2021"

[dependencies]
rand_pcg = "0.3"
rand = { version = "0.8", default-features = false, features = ["nightly"] }

[features]
