set dotenv-load := true

copy-files:
  cp -r ./build/* ../wasmComp
  cp ./build/stone_bg.wasm ../../../static
  cp -r ./build2/* ../../../static
  cp -r ./geodesics/build/bin/* ../../../src/geodesics/
  cp -r ./geodesics/build/bin/* ../../../static/

bindgen:
  wasm-bindgen ./target/wasm32-unknown-unknown/release/bridge2.wasm --target web --remove-producers-section --out-dir ./build
  wasm-bindgen ./target/wasm32-unknown-unknown/release/conduit_particles.wasm --target web --remove-producers-section --out-dir ./build
  wasm-bindgen ./target/wasm32-unknown-unknown/release/cave.wasm --target web --remove-producers-section --out-dir ./build
  wasm-bindgen ./target/wasm32-unknown-unknown/release/stone.wasm --target web --remove-producers-section --out-dir ./build
  wasm-bindgen ./target/wasm32-unknown-unknown/release/tessellation_sandbox.wasm --target web --remove-producers-section --out-dir ./build
  wasm-bindgen ./target/wasm32-unknown-unknown/release/basalt.wasm --target web --remove-producers-section --out-dir ./build
  wasm-bindgen ./target/wasm32-unknown-unknown/release/csg_sandbox.wasm --target web --remove-producers-section --out-dir ./build

  cp ./target/wasm32-unknown-unknown/release/normal_map_gen.wasm ./build2
  cp ./target/wasm32-unknown-unknown/release/texture_crossfade.wasm ./build2
  cp ./target/wasm32-unknown-unknown/release/point_distribute.wasm ./build2
  cp ./target/wasm32-unknown-unknown/release/terrain.wasm ./build2

opt:
  #!/usr/bin/env -S parallel --shebang --ungroup --jobs 6
  wasm-opt ./build/bridge2_bg.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --detect-features --strip-dwarf -c -o ./build/bridge2_bg.wasm --enable-bulk-memory --enable-nontrapping-float-to-int
  wasm-opt ./build/conduit_particles_bg.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --detect-features --strip-dwarf -c -o ./build/conduit_particles_bg.wasm --enable-bulk-memory --enable-nontrapping-float-to-int
  wasm-opt ./build2/normal_map_gen.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --detect-features --strip-dwarf -c -o ./build2/normal_map_gen.wasm --enable-bulk-memory --enable-nontrapping-float-to-int
  wasm-opt ./build2/texture_crossfade.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --detect-features --strip-dwarf -c -o ./build2/texture_crossfade.wasm --enable-bulk-memory --enable-nontrapping-float-to-int
  wasm-opt ./build2/point_distribute.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --detect-features --strip-dwarf -c -o ./build2/point_distribute.wasm --enable-bulk-memory --enable-nontrapping-float-to-int
  wasm-opt ./build/cave_bg.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --detect-features --strip-dwarf -c -o ./build2/cave_bg.wasm --enable-bulk-memory --enable-nontrapping-float-to-int
  wasm-opt ./build2/terrain.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --detect-features --strip-dwarf -c -o ./build2/terrain.wasm --enable-bulk-memory --enable-nontrapping-float-to-int
  wasm-opt ./build/stone_bg.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --detect-features --strip-dwarf -c -o ./build/stone_bg.wasm --enable-bulk-memory --enable-nontrapping-float-to-int
  wasm-opt ./geodesics/build/bin/geodesics.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --detect-features --strip-dwarf -c -o ./geodesics/build/bin/geodesics.wasm --enable-bulk-memory --enable-nontrapping-float-to-int
  wasm-opt ./build/tessellation_sandbox_bg.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --detect-features --strip-dwarf -c -o ./build/tessellation_sandbox_bg.wasm --enable-bulk-memory --enable-nontrapping-float-to-int
  wasm-opt ./build/basalt_bg.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --detect-features --strip-dwarf -c -o ./build/basalt_bg.wasm --enable-bulk-memory --enable-nontrapping-float-to-int
  wasm-opt ./build/csg_sandbox_bg.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --detect-features --strip-dwarf -c -o ./build/csg_sandbox_bg.wasm --enable-bulk-memory --enable-nontrapping-float-to-int

build:
  #!/bin/bash

  rm -rf ./build/*
  RUSTFLAGS="-Ctarget-feature=+simd128" cargo build --release --target wasm32-unknown-unknown --workspace

  just bindgen
  just build-geodesics

clean:
  rm -rf build/*
  rm -rf build2/*
  cd ./geodesics && just clean

build-geodesics:
  #!/bin/bash

  set -e

  cd ./geodesics
  echo "fetch submodules if ./deps/geometry-central/README.md doesn't exist" > /dev/null
  if [ ! -f ./deps/geometry-central/README.md ]; then
    echo "fetching submodules"
    git submodule update --init --recursive
  fi

  echo "need to do full build with CMake if ./build/CMakeCache.txt doesn't exist" > /dev/null
  if [ ! -f ./build/CMakeCache.txt ]; then
    echo "doing full build with CMake"
    just build-all
  else
    just build
  fi

debug:
  cargo build --target wasm32-unknown-unknown --workspace

  just bindgen
  just opt
  just copy-files

# ---

build-basalt:
  RUSTFLAGS="-Ctarget-feature=+simd128" cargo build --release --target wasm32-unknown-unknown --package basalt
  wasm-bindgen ./target/wasm32-unknown-unknown/release/basalt.wasm --target web --remove-producers-section --out-dir ./build
  cp ./build/basalt* ../wasmComp

build-csg-sandbox:
  cargo build --release --target wasm32-unknown-unknown --package csg_sandbox
  wasm-bindgen ./target/wasm32-unknown-unknown/release/csg_sandbox.wasm --target web --remove-producers-section --out-dir ./build
  # wasm-opt ./build/csg_sandbox_bg.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --detect-features --strip-dwarf -c -o ./build/csg_sandbox_bg.wasm --enable-bulk-memory --enable-nontrapping-float-to-int
  cp ./build/csg_sandbox* ../wasmComp
