[package]
name = "bridge2"
version = "0.1.0"
authors = ["Casey Primozic <casey@cprimozic.net>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.82"
nalgebra = "0.31"
rand = { version = "0.8", default-features = false, features = ["nightly"] }
rand_pcg = "0.3"
