// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  UnaryOp = 5,
  BinaryExpr = 7,
  CompareOp = 10,
  Identifier = 16,
  FunctionArg = 18,
  Integer = 22,
  Float = 23,
  ClosureArgs = 28,
  TypeHint = 29,
  ClosureBody = 31
