// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {geoscriptHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: ",`QYQPOOOOQO'#Ca'#CaOtQPO'#C`O#^QPO'#C_O%hQPO'#D[OOQO'#Dh'#DhO%rQPO'#CwO%yQPO'#CxOtQPO'#DPOOQO'#D['#D[OOQO'#DZ'#DZOOQO'#DS'#DSQYQPOOOOQO,58z,58zO&RQPO'#D[OtQPO,58}OtQPO,58}OtQPO,58}OtQPO,58}OtQPO,58}OtQPO,58}OtQPO,58}O&`QPO,59ROtQPO,59TOOQO,58y,58yO'PQPO,59XO'WQPO'#CzOtQPO,59mO']QPO,59mO'bQPO'#DiOOQO,59c,59cO'lQPO,59cO'qQPO'#DlO'|QPO'#DkOOQO'#Dj'#DjOOQO'#Cy'#CyO(UQPO,59dO(ZQPO,59kOOQO-E7Q-E7QO*OQPO1G.iO*YQPO1G.iO*mQPO1G.iO,eQPO1G.iO,oQPO1G.iO.jQPO1G.iO.qQPO1G.iOOQO1G.m1G.mO/pQPO1G.oO0pQPO'#CoO0zQPO'#D[OOQO'#Co'#CoO2UQPO'#DgOOQO'#Df'#DfO2^QPO1G.sOOQO,59f,59fO2cQPO1G/XOtQPO1G/XO3SQPO'#DUO3^QPO,5:TOOQO1G.}1G.}OOQO,5:W,5:WO3fQPO'#DVO3qQPO,5:VO3yQPO1G/OOOQO1G/V1G/VOtQPO,59[O4TQPO'#DTO4_QPO,5:ROOQO7+$_7+$_OOQO7+$s7+$sO4gQPO7+$sO5WQPO,59pOOQO-E7S-E7SOOQO,59q,59qOOQO-E7T-E7TO5bQPO'#C|O6[QPO'#C|OOQO7+$j7+$jO3|QPO7+$jO6cQPO1G.vOOQO,59o,59oOOQO-E7R-E7ROOQO<<H_<<H_OOQO,59h,59hO6mQPO,59hOOQO<<HU<<HUOOQO1G/S1G/S",
  stateData: "6{~O|OSPOS~OUPO[SObWOgTOhTOjUO!PPO!UVO~OUPO[^ObWOgTOhTOjUO!PPO!UVO~OWaOXbOYcO^gO_gO!P_O!Q_O!R`O!S`O!T`O!UbO!VdO!WeO!XfO~OthOURX[RXbRXgRXhRXjRXzRXrRX~P!`ObiOU!OXW!OXX!OXY!OX[!OX^!OX_!OXg!OXh!OXj!OXt!OXz!OX!P!OX!Q!OX!R!OX!S!OX!T!OX!U!OX!V!OX!W!OX!X!OXr!OX~OekOojO~P#}OinO~PtO[pO!U!^P~Of!OXi!OX`!OX~P#}O[!OO~OUPO[!RObWOgTOhTOjUO!PPO!UVO~O`!YP~P&eO[!WO~Oe!YO~Of!ZOi!]X~P!`Oi!]O~OojOf!`X!U!`X~Of!_O!U!_X~O!U!aO~O`!bO~P!`O!R`O!S`O!T`O!XfOUViWViXViYVi[Vi^Vi_VibVigVihVijVitVizVi!UVi!VVi!WVifViiVi`VirVi~O!PVi!QVi~P(bO!PVi!QVi!RVi!SVi!TVi~P(kO!P_O!Q_O~P(bOWaO!P_O!Q_O!R`O!S`O!T`O!XfOUViYVi[Vi^Vi_VibVigVihVijVitVizVi!VVi!WVifViiVi`VirVi~OXVi!UVi~P*wOXbO!UbO~P*wOWaOXbOYcO!P_O!Q_O!R`O!S`O!T`O!UbO!XfOUVi[Vi^Vi_VibVigVihVijVitVizVi!WVifViiVi`VirVi~O!VVi~P,yO!VdO~P,yOWaOXbOYcO!P_O!Q_O!R`O!S`O!T`O!UbO!VdO!WeO!XfO~OU]i[]i^]i_]ib]ig]ih]ij]it]iz]if]ii]i`]ir]i~P.xO`cXfcX~P!`ObiOe!cOW!OXX!OXY!OX^!OX_!OX`!OXf!OX!P!OX!Q!OX!R!OX!S!OX!T!OX!U!OX!V!OX!W!OX!X!OX~Of!dO`!ZX~O`!fO~Ot!gOUui[uibuiguihuijuizuirui~P!`OfxXixX~PtOf!ZOi!]a~O[pOfyX!UyX~Of!_O!U!_a~OojOq!nO~PtO`wXfwX~P&eOf!dO`!Za~Ot!tOUuq[uqbuqguqhuqjuqzuqruq~P!`Ofxaixa~P!`OUpX[pXbpXgpXhpXjpXtpXzpXfpXipX`pXrpX~P!`Or!uO~PYO`difdi~P!`Or!xO~PYOh[gP!SP~",
  goto: "&p!aPPP!b!h#RP!hPPP!hP!hPPP!hP#l#rPPPPPP!h!h#v#yP$SPP!hP!b$Y$d$j$pPPP$v$|PPPPPPPPP&Z&^!h&a&d&g&jXYO[!n!v!PXOQUW[_`abcdegik!Y!Z!a!c!d!n!p!v!PQOQUW[_`abcdegik!Y!Z!a!c!d!n!p!vQ!TiR!r!dT!Si!dRtVQlSQ!^pR!p!aQ!o!aR!w!pQ[OSv[!vR!v!nQ!e!TR!s!eQ![mR!j![Q!`qR!l!`XZO[!n!vWRO[!n!vQ]QQmUQuWQw_Qx`QyaQzbQ{cQ|dQ}eQ!PgS!Qi!dQ!XkQ!h!YQ!i!ZS!m!a!pR!q!cR!ViR!UiRoURsVRrVQqVR!k!_",
  nodeNames: "⚠ LineComment Program ExprStatement UnaryExpr UnaryOp ! BinaryExpr & -> CompareOp FieldAccessExpr Identifier RangeExpr .. ..= ) CallExpr ( FunctionArg Kwarg = , Integer Float ] [ ArrayExpr ClosureExpr ClosureArgs TypeHint : ClosureBody { } ParenthesizedExpr ; DeclarationStatement",
  maxTerm: 62,
  nodeProps: [
    ["isolate", 1,""],
    ["openedBy", 16,"(",25,"["],
    ["closedBy", 18,")",26,"]"]
  ],
  propSources: [geoscriptHighlighting],
  skippedNodes: [0,1],
  repeatNodeCount: 4,
  tokenData: "'s~RmXY!|YZ!|]^!|pq!|qr#Ruv#`vw#exy#ryz#wz{#|{|$R|}$W}!O$]!O!P$j!P!Q%P!Q![%p![!]&T!]!^&Y!^!_&_!_!`&g!`!a&_!c!}&o!}#O'Q#P#Q'V#R#S&o#T#o&o#o#p'[#p#q'a#q#r'n~#RO|~~#WPU~!_!`#Z~#`OY~~#eO!T~~#jPW~vw#m~#rO!V~~#wOb~~#|O`~~$RO!R~~$WO!Q~~$]Of~~$bP!P~!`!a$e~$jOX~~$oP!X~!O!P$r~$wP^~!_!`$z~%PO_~~%UP!S~!P!Q%X~%^SP~OY%XZ;'S%X;'S;=`%j<%lO%X~%mP;=`<%l%X~%uQg~!O!P%{!Q![%p~&QPh~!Q![%{~&YOo~~&_Ot~~&dPY~!_!`#Z~&lPe~!_!`#Z~&tS[~!Q![&o!c!}&o#R#S&o#T#o&o~'VOj~~'[Oi~~'aOq~~'fP!U~#p#q'i~'nO!W~~'sOr~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 1002
})
