// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {literalTokens} from "./tokens"
import {geoscriptHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: ",lQYQROOOOQP'#Cc'#CcO}QRO'#CbO#pQRO'#C`O&QQRO'#CaOOQP'#Dk'#DkO&[QRO'#C|O&cQQO'#DTO&kQRO'#C}O}QRO'#DWOOQP'#Ca'#CaOOQP'#Db'#DbOOQP'#DZ'#DZQYQROOOOQP,58|,58|O&uQRO'#CaO}QRO,59PO}QRO,59PO}QRO,59PO}QRO,59PO}QRO,59PO}QRO,59PO}QRO,59PO'SQQO,59WO}QRO,59YOOQP,58z,58zO'|QRO,59^O(TQQO'#DOO}QRO,59tO(YQQO,59tO(_QQO'#DlOOQP,59h,59hO(iQQO,59hO(nQQO'#DUO(yQQO'#DnOOQO'#Dm'#DmO)RQQO,59oO)WQRO'#DQO*TQRO'#DQOOQP,59i,59iO&nQRO,59iO*[QQO,59rOOQP-E7X-E7XO,SQRO1G.kO,^QRO1G.kO,qQRO1G.kO.oQRO1G.kO0jQRO1G.kO0qQRO1G.kO0xQRO1G.kOOQP1G.r1G.rO1wQRO1G.tO2zQQO'#CtO3UQQO'#CaOOQO'#Ct'#CtO4`QQO'#DjOOQO'#Di'#DiO4hQQO1G.xOOQP,59j,59jO4mQRO1G/`O}QRO1G/`O5aQRO'#D]O5kQQO,5:WOOQP1G/S1G/SOOQO,59p,59pO5sQQO'#D^O6OQQO,5:YOOQP1G/Z1G/ZOOQP,59l,59lO6WQRO,59lOOQP1G/T1G/TOOQP1G/^1G/^O}QRO,59aO6_QRO'#D[O6iQQO,5:UOOQP7+$d7+$dOOQP7+$z7+$zO6qQRO7+$zO7eQQO,59wOOQO-E7Z-E7ZO7oQQO'#DVOOQO,59x,59xOOQO-E7[-E7[OOQP1G/W1G/WO7zQQO1G.{OOQO,59v,59vOOQO-E7Y-E7YOOQP<<Hf<<HfOOQO,59q,59q",
  stateData: "8[~O!TOSQOS~OPTOWPOZVO_WOaSOgXOlTOmTOoUO!VPO!WPO~OPTOWPOZVO_WOa_OgXOlTOmTOoUO!VPO!WPO~OYbOZcO[cO]dO^eO_fOchOdhO!V`O!W`O!XaO!YaO!ZaO![gO~O{iOPSXWSXaSXgSXlSXmSXoSX!RSXvSX~P!rOgjOPTXWTXYTXZTX[TX]TX^TX_TXaTXcTXdTXlTXmTXoTX{TX!RTX!VTX!WTX!XTX!YTX!ZTX![TXvTX~OjlOskO~P$dOnoO~P}OaqOZ!aP~OskOuvO~P}OkTXnTXeTX~P$dOa!SO~OPTOWPOZVO_WOa!VOgXOlTOmTOoUO!VPO!WPO~Oe!]P~P'XOa![O~Oj!^O~Ok!_On!`X~P!rOn!aO~OskOZxXkxX~Ok!cOZ!bX~OZ!eO~OPtXWtXatXgtXltXmtXotX{tX!RtXktXntXetXvtX~P!rOv!fO~PYOe!iO~P!rO!XaO!YaO!ZaO![gOPXiWXiYXiZXi[Xi]Xi^Xi_XiaXicXidXigXilXimXioXi{Xi!RXikXinXieXivXi~O!VXi!WXi~P*cO!VXi!WXi!XXi!YXi!ZXi~P*lO!V`O!W`O~P*cOYbO]dO^eO!V`O!W`O!XaO!YaO!ZaO![gOPXiWXiZXi[XiaXicXidXigXilXimXioXi{Xi!RXikXinXieXivXi~O_fO~P,{OYbO!V`O!W`O!XaO!YaO!ZaO![gOPXiWXiZXi[Xi^Xi_XiaXicXidXigXilXimXioXi{Xi!RXikXinXieXivXi~O]Xi~P.vO]dO~P.vO_Xi~P,{OYbOZcO[cO]dO^eO_fO!V`O!W`O!XaO!YaO!ZaO![gO~OPbiWbiabicbidbigbilbimbiobi{bi!Rbikbinbiebivbi~P1POehXkhX~P!rOgjOj!jOYTXZTX[TX]TX^TX_TXcTXdTXeTXkTX!VTX!WTX!XTX!YTX!ZTX![TX~Ok!kOe!^X~Oe!mO~O{!nOP|iW|ia|ig|il|im|io|i!R|iv|i~P!rOk!PXn!PX~P}Ok!_On!`a~Oa!rOZ!QXk!QX~Ok!cOZ!ba~Ov!uO~PYOe!OXk!OX~P'XOk!kOe!^a~O{!yOP|qW|qa|qg|ql|qm|qo|q!R|qv|q~P!rOk!Pan!Pa~P!rOskOZyXkyX~Oeiikii~P!rOQ!Ymam~",
  goto: "']!cPPPP!d!j#w$bP#wPPPPPP#wP#wPPP#wP${%RPPPPPP#w#w%VP%cPP%i&S&V#wP!d&Y&d&j&pPPP&vPPPPPP&|'P#w'S'V'YXZO]v!gWRO]v!gQ^QQnUSuWxQyXQ{`Q|aQ}bQ!OcQ!PdQ!QeQ!RfQ!ThS!Uj!kQ!]lQ!o!^Q!p!_R!v!j!PYOQUWX]`abcdefhjlvx!^!_!g!j!k!PQOQUWX]`abcdefhjlvx!^!_!g!j!kQ!XjR!w!kT!Wj!kQmSQxWQ!bqR!z!rQwWR!hx!PWOQUWX]`abcdefhjlvx!^!_!g!j!kRrVR!s!cQ]OSz]!gR!gvQ!l!XR!x!lQ!`nR!q!`Q!drR!t!dX[O]v!gR!ZjR!YjRpURtVRsV",
  nodeNames: "⚠ Float LineComment Program ExprStatement Expr UnaryExpr UnaryOp ! BinaryExpr & Pipe -> CompareOp LogicalAndOp LogicalOrOp FieldAccessExpr Identifier RangeExpr .. ..= ) CallExpr ( FunctionArg Kwarg = , Integer BoolLiteral ] [ ArrayExpr ClosureExpr TypeHint : ClosureBody { } ClosureParamList Parameter Parameter ParenthesizedExpr ; DeclarationStatement",
  maxTerm: 64,
  nodeProps: [
    ["isolate", 2,""],
    ["openedBy", 21,"(",30,"["],
    ["closedBy", 23,")",31,"]"]
  ],
  propSources: [geoscriptHighlighting],
  skippedNodes: [0,2],
  repeatNodeCount: 4,
  tokenData: "+U~RqXY#YYZ#Y]^#Ypq#Yqr#_uv#lvw#qxy$Oyz$Tz{$Y{|$_|}$d}!O$i!O!P$v!P!Q%]!Q![%|![!]&U!]!^&Z!^!_&`!_!`&h!`!a&`!c!}&p!}#O'R#P#Q'W#R#S&p#T#Y&p#Y#Z']#Z#h&p#h#i)m#i#o&p#o#p*m#p#q*r#q#r+P~#_O!T~~#dPW~!_!`#g~#lO]~~#qO!Z~~#vPY~vw#y~$OO^~~$TOg~~$YOe~~$_O!X~~$dO!V~~$iOk~~$nP!W~!`!a$q~$vO[~~${P![~!O!P%O~%TPc~!_!`%W~%]Od~~%bP!Y~!P!Q%e~%jSQ~OY%eZ;'S%e;'S;=`%v<%lO%e~%yP;=`<%l%e~&RPl~!Q![%|~&ZOs~~&`O{~~&eP]~!_!`#g~&mPj~!_!`#g~&uSa~!Q![&p!c!}&p#R#S&p#T#o&p~'WOo~~']On~~'bTa~!Q![&p!c!}&p#R#S&p#T#U'q#U#o&p~'vUa~!Q![&p!c!}&p#R#S&p#T#`&p#`#a(Y#a#o&p~(_Ua~!Q![&p!c!}&p#R#S&p#T#g&p#g#h(q#h#o&p~(vUa~!Q![&p!c!}&p#R#S&p#T#X&p#X#Y)Y#Y#o&p~)aSm~a~!Q![&p!c!}&p#R#S&p#T#o&p~)rUa~!Q![&p!c!}&p#R#S&p#T#f&p#f#g*U#g#o&p~*ZUa~!Q![&p!c!}&p#R#S&p#T#i&p#i#j(q#j#o&p~*rOu~~*wPZ~#p#q*z~+PO_~~+UOv~",
  tokenizers: [literalTokens, 0],
  topRules: {"Program":[0,3]},
  tokenPrec: 1064
})
