// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {literalTokens} from "./tokens"
import {geoscriptHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: ",`QYQROOOOQP'#Cb'#CbOwQRO'#CaO#dQRO'#C`O%tQRO'#D]OOQP'#Di'#DiO&OQRO'#CxO&VQQO'#CyOwQRO'#DQOOQP'#D]'#D]OOQP'#D['#D[OOQP'#DT'#DTQYQROOOOQP,58{,58{O&_QRO'#D]OwQRO,59OOwQRO,59OOwQRO,59OOwQRO,59OOwQRO,59OOwQRO,59OOwQRO,59OO&lQQO,59SOwQRO,59UOOQP,58z,58zO'`QRO,59YO'gQQO'#C{OwQRO,59nO'lQQO,59nO'qQQO'#DjOOQP,59d,59dO'{QQO,59dO(QQQO'#DmO(]QQO'#DlOOQO'#Dk'#DkOOQO'#Cz'#CzO(eQQO,59eO(jQQO,59lOOQP-E7R-E7RO*bQRO1G.jO*lQRO1G.jO+PQRO1G.jO,zQRO1G.jO-UQRO1G.jO/SQRO1G.jO/ZQRO1G.jOOQP1G.n1G.nO0YQRO1G.pO1]QQO'#CpO1gQQO'#D]OOQO'#Cp'#CpO2qQQO'#DhOOQO'#Dg'#DgO2yQQO1G.tOOQP,59g,59gO3OQRO1G/YOwQRO1G/YO3rQRO'#DVO3|QQO,5:UOOQP1G/O1G/OOOQO,5:X,5:XO4UQQO'#DWO4aQQO,5:WO4iQRO1G/POOQP1G/W1G/WOwQRO,59]O4sQRO'#DUO4}QQO,5:SOOQP7+$`7+$`OOQP7+$t7+$tO5VQRO7+$tO5yQQO,59qOOQO-E7T-E7TOOQO,59r,59rOOQO-E7U-E7UO6TQRO'#C}O7QQRO'#C}OOQP7+$k7+$kO4lQRO7+$kO7XQQO1G.wOOQO,59p,59pOOQO-E7S-E7SOOQP<<H`<<H`OOQP,59i,59iO7cQRO,59iOOQP<<HV<<HVOOQP1G/T1G/T",
  stateData: "7p~O}OSQOS~OPTOVPO]SOcWOhTOiTOkUO!QPO!VVO~OPTOVPO]^OcWOhTOiTOkUO!QPO!VVO~OXaOYbOZcO_gO`gO!Q_O!R_O!S`O!T`O!U`O!VbO!WdO!XeO!YfO~OuhOPSXVSX]SXcSXhSXiSXkSX{SXsSX~P!fOciOP!PXV!PXX!PXY!PXZ!PX]!PX_!PX`!PXh!PXi!PXk!PXu!PX{!PX!Q!PX!R!PX!S!PX!T!PX!U!PX!V!PX!W!PX!X!PX!Y!PXs!PX~OfkOpjO~P$WOjnO~PwO]pO!V!_P~Og!PXj!PXa!PX~P$WO]!OO~OPTOVPO]!ROcWOhTOiTOkUO!QPO!VVO~Oa!ZP~P&qO]!WO~Of!YO~Og!ZOj!^X~P!fOj!]O~OpjOg!aX!V!aX~Og!_O!V!`X~O!V!aO~Oa!bO~P!fO!S`O!T`O!U`O!YfOPWiVWiXWiYWiZWi]Wi_Wi`WicWihWiiWikWiuWi{Wi!VWi!WWi!XWigWijWiaWisWi~O!QWi!RWi~P(qO!QWi!RWi!SWi!TWi!UWi~P(zO!Q_O!R_O~P(qOXaO!Q_O!R_O!S`O!T`O!U`O!YfOPWiVWiZWi]Wi_Wi`WicWihWiiWikWiuWi{Wi!WWi!XWigWijWiaWisWi~OYWi!VWi~P+ZOYbO!VbO~P+ZOXaOYbOZcO!Q_O!R_O!S`O!T`O!U`O!VbO!YfOPWiVWi]Wi_Wi`WicWihWiiWikWiuWi{Wi!XWigWijWiaWisWi~O!WWi~P-`O!WdO~P-`OXaOYbOZcO!Q_O!R_O!S`O!T`O!U`O!VbO!WdO!XeO!YfO~OP^iV^i]^i_^i`^ic^ih^ii^ik^iu^i{^ig^ij^ia^is^i~P/bOadXgdX~P!fOciOf!cOX!PXY!PXZ!PX_!PX`!PXa!PXg!PX!Q!PX!R!PX!S!PX!T!PX!U!PX!V!PX!W!PX!X!PX!Y!PX~Og!dOa![X~Oa!fO~Ou!gOPviVvi]vicvihviivikvi{visvi~P!fOgyXjyX~PwOg!ZOj!^a~O]pOgzX!VzX~Og!_O!V!`a~OpjOr!nO~PwOaxXgxX~P&qOg!dOa![a~Ou!tOPvqVvq]vqcvqhvqivqkvq{vqsvq~P!fOgyajya~P!fOPqXVqX]qXcqXhqXiqXkqXuqX{qXgqXjqXaqXsqX~P!fOs!uO~PYOaeigei~P!fOs!xO~PYOQ!Ti]i~",
  goto: "&q!bPPPP!c!i#SP!iPPP!iP!iPPP!iP#m#sPPPPPP!i!i#w#zP$TPP!iP!c$Z$e$k$qPPP$w$}PPPPPPPPP&[&_!i&b&e&h&kXYO[!n!v!PXOQUW[_`abcdegik!Y!Z!a!c!d!n!p!v!PQOQUW[_`abcdegik!Y!Z!a!c!d!n!p!vQ!TiR!r!dT!Si!dRtVQlSQ!^pR!p!aQ!o!aR!w!pQ[OSv[!vR!v!nQ!e!TR!s!eQ![mR!j![Q!`qR!l!`XZO[!n!vWRO[!n!vQ]QQmUQuWQw_Qx`QyaQzbQ{cQ|dQ}eQ!PgS!Qi!dQ!XkQ!h!YQ!i!ZS!m!a!pR!q!cR!ViR!UiRoURsVRrVQqVR!k!_",
  nodeNames: "⚠ Float LineComment Program ExprStatement UnaryExpr UnaryOp ! BinaryExpr & -> CompareOp FieldAccessExpr Identifier RangeExpr .. ..= ) CallExpr ( FunctionArg Kwarg = , Integer BoolLiteral ] [ ArrayExpr ClosureExpr ClosureArgs TypeHint : ClosureBody { } ParenthesizedExpr ; DeclarationStatement",
  maxTerm: 63,
  nodeProps: [
    ["isolate", 2,""],
    ["openedBy", 17,"(",26,"["],
    ["closedBy", 19,")",27,"]"]
  ],
  propSources: [geoscriptHighlighting],
  skippedNodes: [0,2],
  repeatNodeCount: 4,
  tokenData: "+U~RqXY#YYZ#Y]^#Ypq#Yqr#_uv#lvw#qxy$Oyz$Tz{$Y{|$_|}$d}!O$i!O!P$v!P!Q%]!Q![%|![!]&U!]!^&Z!^!_&`!_!`&h!`!a&`!c!}&p!}#O'R#P#Q'W#R#S&p#T#Y&p#Y#Z']#Z#h&p#h#i)m#i#o&p#o#p*m#p#q*r#q#r+P~#_O}~~#dPV~!_!`#g~#lOZ~~#qO!U~~#vPX~vw#y~$OO!W~~$TOc~~$YOa~~$_O!S~~$dO!R~~$iOg~~$nP!Q~!`!a$q~$vOY~~${P!Y~!O!P%O~%TP_~!_!`%W~%]O`~~%bP!T~!P!Q%e~%jSQ~OY%eZ;'S%e;'S;=`%v<%lO%e~%yP;=`<%l%e~&RPh~!Q![%|~&ZOp~~&`Ou~~&ePZ~!_!`#g~&mPf~!_!`#g~&uS]~!Q![&p!c!}&p#R#S&p#T#o&p~'WOk~~']Oj~~'bT]~!Q![&p!c!}&p#R#S&p#T#U'q#U#o&p~'vU]~!Q![&p!c!}&p#R#S&p#T#`&p#`#a(Y#a#o&p~(_U]~!Q![&p!c!}&p#R#S&p#T#g&p#g#h(q#h#o&p~(vU]~!Q![&p!c!}&p#R#S&p#T#X&p#X#Y)Y#Y#o&p~)aSi~]~!Q![&p!c!}&p#R#S&p#T#o&p~)rU]~!Q![&p!c!}&p#R#S&p#T#f&p#f#g*U#g#o&p~*ZU]~!Q![&p!c!}&p#R#S&p#T#i&p#i#j(q#j#o&p~*rOr~~*wP!V~#p#q*z~+PO!X~~+UOs~",
  tokenizers: [literalTokens, 0],
  topRules: {"Program":[0,3]},
  tokenPrec: 1038
})
