// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Float = 1,
  LineComment = 2,
  Program = 3,
  UnaryOp = 6,
  BinaryExpr = 8,
  CompareOp = 11,
  FieldAccessExpr = 12,
  Identifier = 13,
  FunctionArg = 20,
  Integer = 24,
  BoolLiteral = 25,
  ClosureArgs = 30,
  TypeHint = 31,
  ClosureBody = 33
