// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  UnaryOp = 5,
  BinaryExpr = 7,
  CompareOp = 9,
  Identifier = 15,
  Integer = 18,
  Float = 19,
  ClosureArgs = 24,
  TypeHint = 25,
  ClosureBody = 27
