import { styleTags, tags as t } from '@lezer/highlight';

export const geoscriptHighlighting = styleTags({
  Identifier: t.variableName,
  'CallExpr/Identifier': t.function(t.variableName),
  'ClosureParamList/Identifier': t.function(t.definition(t.variableName)),
  'TypeHint/Identifier': t.typeName,
  'FieldAccessExpr/Identifier': t.propertyName,
  LineComment: t.lineComment,
  Integer: t.integer,
  Float: t.float,
  BoolLiteral: t.bool,
  NilLiteral: t.null,
  'StringLiteral/...': t.typeName, // default gruvbox theme makes strings white which I don't like
  '"+"': t.arithmeticOperator,
  '"-"': t.arithmeticOperator,
  '"/"': t.arithmeticOperator,
  '"%"': t.arithmeticOperator,
  '"||"': t.logicOperator,
  '"&&"': t.logicOperator,
  '"&"': t.bitwiseOperator,
  '"|"': t.bitwiseOperator,
  '"^"': t.bitwiseOperator,
  '">="': t.compareOperator,
  '"<="': t.compareOperator,
  '"=="': t.compareOperator,
  CompareOp: t.compareOperator,
  '"!="': t.compareOperator,
  '">"': t.compareOperator,
  '"<"': t.compareOperator,
  '"="': t.definitionOperator,
  '".."': t.punctuation,
  '"..="': t.punctuation,
  '( )': t.paren,
  '[ ]': t.squareBracket,
  '{ }': t.brace,
  ',': t.separator,
  ';': t.separator,
  If: t.keyword,
  ElseIf: t.keyword,
  Else: t.keyword,
  Return: t.keyword,
  Break: t.keyword,
});
