code:
  RUSTFLAGS="--cfg tokio_unstable --cfg foundations_unstable" code .

generate-default-config:
  RUSTFLAGS="--cfg tokio_unstable --cfg foundations_unstable" RUST_LOG=debug cargo run -- --generate default-config.yml

docker-build:
  docker build --network host -t ameo/geoscript-backend:latest .

run:
  RUSTFLAGS="--cfg tokio_unstable --cfg foundations_unstable" RUST_LOG=debug cargo run -- --config=config.yml

release:
  RUSTFLAGS="--cfg tokio_unstable --cfg foundations_unstable" RUST_LOG=debug cargo run --release -- --config=config.yml

migrate:
  sqlx migrate run --source migrations

build-and-deploy:
  #!/bin/bash

  just docker-build
  docker save ameo/geoscript-backend:latest | bzip2 > /tmp/geoscript-backend.tar.bz2
  scp /tmp/geoscript-backend.tar.bz2 debian@ameo.dev:/tmp/geoscript-backend.tar.bz2
  ssh debian@ameo.dev -t 'cat /tmp/geoscript-backend.tar.bz2 | bunzip2 | docker load && docker kill geoscript-backend && docker container rm geoscript-backend && docker run   --name geoscript-backend   --restart=always   -d   --net host   -v /opt/conf/dream/geoscript-backend.yml:/opt/conf.yml   -e RUST_LOG=info   ameo/geoscript-backend:latest   /usr/local/bin/geoscript-backend --config /opt/conf.yml && rm /tmp/geoscript-backend.tar.bz2'
