build-all:
  #!/bin/bash

  mkdir -p build
  cd build
  emcmake cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=emcc -DCMAKE_CXX_COMPILER=em++ -DEMSCRIPTEN=True ..
  echo "There's some compiler issue with Emscripten or otherwise that causes some code in this file to not compile."
  echo "This patched version works around it by just removing it, and it doesn't seem to cause any issues with the geodesics code."
  cp ../src/AmbiVector_PATCH.h ./deps/geometry-central/deps/eigen-src/Eigen/src/SparseCore/AmbiVector.h
  cd -
  just build

build:
  #!/bin/bash

  mkdir -p build
  cd build
  make -j24

  echo "Add the export to make it a proper ESM if it doesn't exist already in the last 5 lines of the file." > /dev/null
  if ! tail -n 5 ./bin/geodesics.js | grep -q "export { Geodesics }"; then
    echo "export { Geodesics }" >> ./bin/geodesics.js
  fi

clean:
  rm -rf build
