[package]
name = "stone"
version = "0.1.0"
authors = ["Casey Primozic <casey@cprimozic.net>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.82"
lyon = "1.0"
common = { path = "../common" }
console_error_panic_hook = "0.1"
