import fs from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';

import { SCENE_REGISTRY, type SceneRegistryEntry } from './sceneRegistry';

/**
 * Vite plugin: writes a per-scene SvelteKit page for every entry in
 * `SCENE_REGISTRY` under `src/routes/(generated)/<route>/+page.{svelte,server.ts}`.
 *
 * Why this exists
 * ---------------
 * SvelteKit emits `<link rel="modulepreload">` (HTTP `Link` headers) in the
 * SSR'd response for static-import deps it can resolve at build time via
 * `find_deps`.  By giving each scene a generated page that statically imports
 * its `processLoadedScene`, the scene's chunk + transitive deps preload in
 * parallel with the entry/app chunks instead of waterfalling behind them.
 *
 * Critical constraint
 * -------------------
 * The generated `+page.svelte` must NOT (transitively) statically import any
 * module that has dynamic-import edges to all scene chunks (`SCENE_REGISTRY`
 * doesn't, but a hypothetical `ScenesByName`-style map would).  SvelteKit's
 * `find_deps` walks `chunk.dynamicImports` with `add_js=false` AND marks them
 * `seen` — so a later static-edge visit to the same chunk is silently skipped,
 * dropping the active scene's deps from the modulepreload set.
 *
 * Practical implications:
 *   - `Viz.svelte` and `viz/index.ts` use `import type` only for `SceneDef`
 *     and friends — never the runtime `SCENE_REGISTRY`.
 *   - The generated `+page.svelte` embeds scene metadata as a JSON literal
 *     rather than reading it from a runtime registry.
 *   - The generated `+page.server.ts` *can* read from the registry (server
 *     code doesn't affect the client chunk graph).
 */

const PROJECT_ROOT = process.cwd();
const ROUTES_OUTPUT_DIR = path.join(PROJECT_ROOT, 'src/routes/(generated)');
const GENERATED_HEADER_SVELTE = '<!-- AUTO-GENERATED by viteGeneratedScenesPlugin.ts.  Do not edit. -->\n';
const GENERATED_HEADER_TS = '// AUTO-GENERATED by viteGeneratedScenesPlugin.ts.  Do not edit.\n';

const generatePageSvelte = (sceneName: string, entry: SceneRegistryEntry): string => {
  const { modulePath, ...sceneDefData } = entry;
  return `${GENERATED_HEADER_SVELTE}<script lang="ts">
  import { processLoadedScene } from '${modulePath}';
  import { browser } from '$app/environment';
  import { onDestroy } from 'svelte';

  import Viz from 'src/viz/Viz.svelte';
  import type { SceneDef } from 'src/viz/scenes';
  import { GeoscriptExecutor } from 'src/geoscript/geoscriptExecutor';
  import type { PageData } from './$types';

  const sceneName = '${sceneName}';
  const sceneDef: SceneDef = {
    ...${JSON.stringify(sceneDefData)},
    sceneLoader: () => processLoadedScene,
  };

  export let data: PageData;

  let geoscriptExecutor: GeoscriptExecutor | undefined = undefined;
  let executorSceneName: string | null = null;

  $: if (browser) {
    const wantExecutor = !!data.levelDef;
    if (wantExecutor && executorSceneName !== data.sceneName) {
      geoscriptExecutor?.terminate();
      geoscriptExecutor = new GeoscriptExecutor();
      executorSceneName = data.sceneName;
    } else if (!wantExecutor && geoscriptExecutor) {
      geoscriptExecutor.terminate();
      geoscriptExecutor = undefined;
      executorSceneName = null;
    }
  }

  onDestroy(() => {
    geoscriptExecutor?.terminate();
    geoscriptExecutor = undefined;
    executorSceneName = null;
  });
</script>

<svelte:head>
  {#each data.preloadUrls ?? [] as url}
    <link rel="preload" as="fetch" crossorigin="anonymous" href={url} />
  {/each}
</svelte:head>

<Viz {sceneName} userData={data.levelDef ?? undefined} {geoscriptExecutor} {sceneDef} />
`;
};

const generatePageServer = (sceneName: string, entry: SceneRegistryEntry): string => {
  if (entry.useSceneDef) {
    return `${GENERATED_HEADER_TS}import { loadLevelData } from 'src/viz/levelDef/loadLevelData.server';
import { getScenePreloadUrls } from 'src/viz/levelDef/preloadUrls';
import type { PageServerLoad } from './$types';

export const load: PageServerLoad = async () => {
  const sceneName = '${sceneName}';
  const levelDef = await loadLevelData(sceneName);
  return { sceneName, levelDef, preloadUrls: getScenePreloadUrls(levelDef) };
};
`;
  }
  return `${GENERATED_HEADER_TS}import { getScenePreloadUrls } from 'src/viz/levelDef/preloadUrls';
import type { PageServerLoad } from './$types';

export const load: PageServerLoad = async () => {
  return { sceneName: '${sceneName}', levelDef: null, preloadUrls: getScenePreloadUrls(null) };
};
`;
};

const writeIfChanged = (filePath: string, content: string): boolean => {
  try {
    if (fs.readFileSync(filePath, 'utf8') === content) {
      return false;
    }
  } catch {
    /* file doesn't exist yet */
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  return true;
};

const cleanStaleScenes = (validSceneNames: Set<string>) => {
  if (!fs.existsSync(ROUTES_OUTPUT_DIR)) {
    return;
  }
  for (const entry of fs.readdirSync(ROUTES_OUTPUT_DIR)) {
    if (!validSceneNames.has(entry)) {
      fs.rmSync(path.join(ROUTES_OUTPUT_DIR, entry), { recursive: true, force: true });
    }
  }
};

const generateAll = () => {
  const sceneNames = new Set(Object.keys(SCENE_REGISTRY));
  cleanStaleScenes(sceneNames);

  for (const [sceneName, entry] of Object.entries(SCENE_REGISTRY)) {
    const sceneDir = path.join(ROUTES_OUTPUT_DIR, sceneName);
    writeIfChanged(path.join(sceneDir, '+page.svelte'), generatePageSvelte(sceneName, entry));
    writeIfChanged(path.join(sceneDir, '+page.server.ts'), generatePageServer(sceneName, entry));
  }
};

export const generatedScenesPlugin = (): Plugin => ({
  name: 'generated-scene-routes',
  // `config()` runs before SvelteKit's plugin sees `configResolved`, so the
  // generated files exist on disk before SvelteKit walks `src/routes/`.  Vite
  // also tracks this plugin file's static imports (including `sceneRegistry.ts`)
  // as config deps — editing the registry restarts the dev server, which
  // re-runs `config()` with the fresh data.
  config() {
    generateAll();
  },
});
