// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * BasicGameBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PlayResponse
 */
export interface PlayResponse {
    /**
     * 
     * @type {string}
     * @memberof PlayResponse
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlayResponse
     */
    playerId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlayResponse
     */
    playerUserName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlayResponse
     */
    mapId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PlayResponse
     */
    playLength?: number;
    /**
     * 
     * @type {Date}
     * @memberof PlayResponse
     */
    timeSubmitted?: Date;
}

/**
 * Check if a given object implements the PlayResponse interface.
 */
export function instanceOfPlayResponse(value: object): value is PlayResponse {
    return true;
}

export function PlayResponseFromJSON(json: any): PlayResponse {
    return PlayResponseFromJSONTyped(json, false);
}

export function PlayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'playerId': json['playerId'] == null ? undefined : json['playerId'],
        'playerUserName': json['playerUserName'] == null ? undefined : json['playerUserName'],
        'mapId': json['mapId'] == null ? undefined : json['mapId'],
        'playLength': json['playLength'] == null ? undefined : json['playLength'],
        'timeSubmitted': json['timeSubmitted'] == null ? undefined : (new Date(json['timeSubmitted'])),
    };
}

export function PlayResponseToJSON(json: any): PlayResponse {
    return PlayResponseToJSONTyped(json, false);
}

export function PlayResponseToJSONTyped(value?: PlayResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'playerId': value['playerId'],
        'playerUserName': value['playerUserName'],
        'mapId': value['mapId'],
        'playLength': value['playLength'],
        'timeSubmitted': value['timeSubmitted'] == null ? undefined : ((value['timeSubmitted']).toISOString()),
    };
}

