/* tslint:disable */
/* eslint-disable */
/**
 * BasicGameBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerLogin
 */
export interface PlayerLogin {
    /**
     * 
     * @type {string}
     * @memberof PlayerLogin
     */
    username: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlayerLogin
     */
    password: string | null;
}

/**
 * Check if a given object implements the PlayerLogin interface.
 */
export function instanceOfPlayerLogin(value: object): value is PlayerLogin {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function PlayerLoginFromJSON(json: any): PlayerLogin {
    return PlayerLoginFromJSONTyped(json, false);
}

export function PlayerLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerLogin {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function PlayerLoginToJSON(json: any): PlayerLogin {
    return PlayerLoginToJSONTyped(json, false);
}

export function PlayerLoginToJSONTyped(value?: PlayerLogin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

